version: '3.9'
services:
  app:
    image: 'node:16-alpine'
    user: 'node'
    working_dir: /home/node/app
    expose:
      - '3000'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: 'npm start'
